---
- name: get Mirador from source
  git:
    repo: https://github.com/IIIF/mirador.git
    version: "{{ mirador_version }}"
    dest: "{{ mirador_src }}"

- name: get requirmented node packages via npm
  npm: "path={{ mirador_src }} state=present"
- name: get required packages via bower
  bower: "path={{ mirador_src }} state=present"
- name: running grunt
  command: grunt server &
  args:
    chdir: "{{ mirador_src }}"
