---
- name: update npm to version 3.
  npm: name=npm state=latest global=yes
- name: install required npm packages
  npm: name={{ item }} global=yes state=present
  with_items:
    - grunt-cli
    - bower
- include: aswebuser.yml
  become_user: "{{ mirador_user }}"
