---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  roles_path: roles
  hosts: mirador
  require_ansible_repo: true
  ansible_verbose: true
  # ansible_version: latest
  require_chef_for_busser: false
  playbook: mirador.yml

platforms:
- name: ubuntu-14.04
  driver_plugin: vagrant
  driver_config:
    box: "ubuntu/trusty64"
    network:
      - ["forwarded_port", {guest: 8000, host: 8000}]
    cache:
      auto_detect: true
      scope: ":box"

- name: ubuntu-16.04
  driver_plugin: vagrant
  driver_config:
    box: xenial64
    box_url: https://s3.amazonaws.com/atg-vagrant-boxes/xenial64.box
    network:
      - ["forwarded_port", {guest: 8000, host: 8001}]
    cache:
      auto_detect: true
      scope: ":box"
  provisioner:
    require_ansible_omnibus: true

- name: bento-16.04
  driver_plugin: vagrant
  driver_config:
    box: bento/ubuntu-16.04;
    network:
      - ["forwarded_port", {guest: 8000, host: 8002}]
    cache:
      auto_detect: true
      scope: ":box"

verifier:
  name: serverspec
  sudo_path: true

suites:
  - name: default
    verifier:
      patterns:
        - roles/*/spec/spec.rb
  - name: dev
    driver_config:
      synced_folders:
        - ['src', '/srv/mirador']
